name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Restore NuGet packages
      run: nuget restore
      
    - name: Publish to folder
      run: msbuild

    - name: Publish to folder
      run: msbuild /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=./published/ /p:PackageAsSingleFile=false

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ehnetframework00'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2589cf4de74440bcae4c8312aaa79619 }}
        package: ./published/
